<?php
/**
 * @author    Sutunam
 * @copyright Copyright (c) 2024 Sutunam (http://www.sutunam.com/)
 */

declare(strict_types=1);

use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var Product $product */
$product = $block->getData('product');

if (!$product) {
    return;
}

$showStockStatusText = $block->getData('show_stock_status_text');
?>
<div class="text-right">
    <?php if ($product->getIsSalable()): ?>
        <p class="flex items-center justify-end align-middle available gap-x-2 stock"
            title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>">
            <span class="w-3 h-3 bg-green-500 rounded-full shrink-0"></span>
            <?php if ($showStockStatusText): ?>
            <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
            <?php endif; ?>
        </p>
    <?php else: ?>
        <p class="flex items-center justify-end align-middle gap-x-2 unavailable stock"
            title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>">
            <span class="w-3 h-3 bg-red-500 rounded-full shrink-0"></span>
            <?php if ($showStockStatusText): ?>
            <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
            <?php endif; ?>
        </p>
    <?php endif; ?>
</div>
